### ISSUE TITLE
Page de confirmation après création de compte

### ISSUE THREAD

**Issue by stephmnt** [jeunes-democrates/covoiturage-jdem#1]
Il manque une page de confirmation après la création de compte lorsqu'on envoie le formulaire pour dire merci, bienvenue, confirmez votre compte, checkez vos mails. etc.

**Comment by StephaneManet** [comment]
Quand on propose un trajet, si on check "aller" ou "retour" après avoir rempli tous les champs ça efface les champs de formulaires. Ça vaut le coup de prévenir avant ou de bloquer les champs tant que celui-ci n'est pas checké. (et pourquoi je peux pas aller ailleurs qu'à Guidel ?)

**Comment by StephaneManet** [comment]
Quand je valide le formulaire de création de trajet, le serveur me renvoie une Server Error (500).

**Comment by stephmnt** [comment]
D'ailleurs il n'y a pas de procédure de confirmation de création de compte ou en tout cas je n'en ai pas reçu.

**Comment by Brachamul** [comment]
Résolu avec un message de confirmation de la création du compte, et un login automatique après création du compte.
